### ISSUE TITLE
PCLink

### ISSUE THREAD

**Issue by jkleiser** [schierlm/OberonEmulator#5]
What is the purpose with the PCLink option when using the OberonEmulator.jar?

**Comment by schierlm** [comment]
It will open a PCLink window which you can drag&drop files too, which will then be transferred using PCLink protocol via the (virtual) serial port to the emulator. So you need to run PCLink inside the emulator before you can drop files, but then it is an easy way to quickly get many (source code) files into the Emulator.

If you do not want to use PCLink, you can also use clipboard integration and copy&paste every file individually :)

Is it now clearer? Then feel free to close the issue. :)

**Comment by jkleiser** [comment]
Thanks!
